# Generated by Django 5.0.6 on 2026-08-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Entreprise')),
                ('service_type', models.CharField(choices=[('statistique', 'Site statistique'), ('dynamique', 'Site dynamique'), ('desktop', 'Application desktop'), ('autre', 'Autre')], max_length=50, verbose_name='Type de service')),
                ('message', models.TextField(verbose_name='Message')),
                ('budget', models.CharField(blank=True, max_length=100, verbose_name='Budget estimé')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('read', 'Lu'), ('contacted', 'Contacté'), ('converted', 'Converti'), ('archived', 'Archivé')], default='new', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demande de contact',
                'verbose_name_plural': 'Demandes de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Abonné newsletter',
                'verbose_name_plural': 'Abonnés newsletter',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon_name', models.CharField(max_length=50, verbose_name="Nom de l'icône (Lucide)")),
                ('features', models.JSONField(blank=True, default=list, verbose_name='Fonctionnalités')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Témoignage')),
                ('author', models.CharField(max_length=100, verbose_name='Auteur')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Poste')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Entreprise')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Note (1-5)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-created_at'],
            },
        ),
    ]
